# global configuration
safe: false

# Site settings
title: uncommonsense
email: 
description: > # this means to ignore newlines until "baseurl:"
  uncommonsense
baseurl: "uncommonsense" # the subpath of your site, e.g. /blog/
url: "http://localhost:4012" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Serve settings
port: 4012
